# https://alacritty.org/config-alacritty.html
import = [

    # "~/.config/alacritty/themes/themes/aura.toml"
    # https://github.com/catppuccin/catppuccin?tab=readme-ov-file
    # curl -LO --output-dir ~/.config/alacritty/themes/ https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

live_config_reload = true



[bell]
animation = "EaseOutExpo"

duration = 0

# [shell]
# args = ["-l", "-c", "tmux attach || tmux"]
# program = "/bin/zsh"


[colors]
draw_bold_text_with_bright_colors = true

# [[colors.indexed_colors]]
# color = "0xF8BD96"
# index = 16
#

# [[colors.indexed_colors]]

# color = "0xF5E0DC"
# index = 17
#
[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"

cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

[colors.normal]

black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[cursor]
blink_interval = 500

blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Beam"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = false
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
startup_mode = "Maximized"
# position = { x = 400, y = 200 }
# dimensions = { columns = 80, lines = 25 }
padding.x = 10
padding.y = 10

decorations = "Buttonless"
decorations_theme_variant = "Dark"
# decorations = "full"
resize_increments = true

option_as_alt = "Both"

[scrolling]
history = 9999

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"


[font.normal]
family = "JetBrainsMono NF"
style = "Regular"


[font]
size = 20


[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", mode = "Vi|Search", action = "ClearSelection" },
  { key = "Insert", mods = "Shift", action = "Paste" }
]

# [hints]
# enabled = [
#   { regex = "\bhttps?://[^\s]+", hyperlinks = true, post_processing = true, persist = true, action = "Copy", <binding>, <mouse> },]

[[hints.enabled]]
# command = "xdg-open" # On Linux/BSD
command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
